# Model arguments
model_name_or_path: meta-llama/Llama-2-7b-hf
# checkpoint_path: /home/quantinx/finetuning-LLM/data/phi-sft-lora/checkpoint-50
cache_dir: /home/quantinx/models/
torch_dtype: auto
use_flash_attention_2: false

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrachat_200k: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
bf16: false
do_eval: false
evaluation_strategy: epoch
load_in_4bit: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: zephyr-7b-sft-lora
# hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
# max_seq_length: 2048
# max_steps: -1
num_train_epochs: 3
output_dir: data/llama-sft-lora
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 4
# push_to_hub: true
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 50 
save_total_limit: null
seed: 42
warmup_ratio: 0.1
